chore: bump k8s deps to v1.29.3 and controller-runtime to v0.17.2
Azure/azure-workload-identity pull request #1292
Opened 2024-03-18 20:48 UTC by aramase

- bump k8s deps to v1.29.3 and controller-runtime to v0.17.2

2024-04-26 18:54 UTC, aramase commented
I've added a unit test in https://github.com/Azure/azure-workload-identity/pull/1292/commits/9640c5881222828a1d9decf0119bcad0222a5c7b to assert the existing failure and the bump of deps fix it.

```bash
=== RUN   TestHandle/pod_has_the_required_label,_restart_policy_in_init_container
    webhook_test.go:806: expected no remove patches, got: {remove /spec/initContainers/0/restartPolicy <nil>}
```

2024-05-02 19:51 UTC, enj requested changes

2024-05-02 19:51 UTC, enj commented on cmd/webhook/main.go
> +	case "", "1.0":
Empty string should error.

2024-05-02 20:10 UTC, aramase commented on cmd/webhook/main.go
> +	case "", "1.0":
done!

2024-05-02 20:44 UTC, enj approved these changes

2024-05-02 20:44 UTC, merged