feat: allow proxies to be injected using a native sidecar
Azure/azure-workload-identity pull request #1442
Opened 2024-08-21 10:04 UTC by devjoes

**Reason for Change**:

Fixes [Issue 773](https://github.com/Azure/azure-workload-identity/issues/773) by using [native sidecars](https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/) so that pods exit cleanly when running as cronjobs, currently azwi sidecar prevents the pod from terminating. 

It also addresses an annoyance where the first container in the pod is the proxy, so any `kubectl` commands target that container, previously I was working around this by adding the [default-container](https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/) annotation.

I've kept the current behaviour as the default because this change requires at least k8s 1.28, adding the annotation `azure.workload.identity/use-native-sidecar` enables native sidecars. But it seems to work well so at some point in the future you could just make this the default behaviour. 

No

No

**Requirements**

- [X] squashed commits
- [X] included documentation
- [X] added unit tests and e2e tests (if applicable).

**Issue Fixed**:

Fixes #733

**Please answer the following questions with yes/no**:

Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?

- [ ] yes
- [X] no

**Notes for Reviewers**:
Tested on v1.30.0-eks-fff26e3

2024-08-21 10:06 UTC, devjoes commented
@microsoft-github-policy-service agree

2024-09-09 09:49 UTC, devjoes commented
@aramase @enj any update on this PR? I've just rebased it

2025-02-13 18:45 UTC, devjoes commented
@bench I think that this repo is dead tbh. I'm going to get on to our account managers and see if they can talk to whoever is meant to be in charge of it

2025-02-26 00:47 UTC, aramase requested changes
Please also add a e2e test [here](https://github.com/Azure/azure-workload-identity/blob/main/test/e2e/proxy_test.go) to validate the new annotation.

2025-02-26 00:47 UTC, aramase commented on docs/book/src/topics/service-account-labels-and-annotations.md
> +| `azure.workload.identity/use-native-sidecar`               | If injected then the proxy sidecar should be injected as a native sidecar init container instead of a container. Native sidecars are ter
Add a note about the minimum required kubernetes version this annotation can be used.

2025-02-26 00:47 UTC, aramase commented on pkg/webhook/webhook.go
> +		}
```suggestion
                var restartPolicy *corev1.ContainerRestartPolicy
		if useNativeSidecar {
			restartPolicy = ptr.To(corev1.ContainerRestartPolicyAlways)
		}
		pod.Spec.Containers = m.injectProxySidecarContainer(pod.Spec.Containers, proxyPort, restartPolicy)
```

2025-02-26 00:47 UTC, aramase commented on pkg/webhook/webhook.go
> +			if strings.HasPrefix(container.Image, fmt.Sprintf("%s:", imageRepository)) || container.Name == ProxySidecarContainerName {
this check was removed as part of https://github.com/Azure/azure-workload-identity/pull/1443

2025-02-26 00:47 UTC, aramase commented on pkg/webhook/webhook.go
> +
```suggestion
```

2025-02-26 00:47 UTC, aramase commented on pkg/webhook/webhook_test.go
> +			containers := m.injectProxySidecarContainer(test.containers, proxyPort, nil)
Update this table test to include restart policy and ensure the return result contains the desired restart policy

2025-02-26 01:48 UTC, enj commented on docs/book/src/topics/service-account-labels-and-annotations.md
> +| `azure.workload.identity/use-native-sidecar`               | If injected then the proxy sidecar should be injected as a native sidecar init container instead of a container. Native sidecars are ter
This is the wrong approach IMO.  I think we should instead detect at runtime (once at webhook start up time) if the cluster supports native sidecars, and if it does, we should simply always use them for the proxy sidecar.  If for some reason we cannot detect this at runtime, we can make it a CLI flag based config to the webhook (possibly enabled by default since in a few days Kube v1.30 will be the oldest supported upstream version).

2025-03-11 11:52 UTC, devjoes commented on docs/book/src/topics/service-account-labels-and-annotations.md
> +| `azure.workload.identity/use-native-sidecar`               | If injected then the proxy sidecar should be injected as a native sidecar init container instead of a container. Native sidecars are ter
I've updated the PR to detect the version of k8s used and automatically use a native sidecar if it is supported

2025-03-11 11:53 UTC, devjoes commented on pkg/webhook/webhook.go
> +		}
I don't think this will work as native sidecars need to be init containers not containers

2025-03-11 11:53 UTC, devjoes commented on pkg/webhook/webhook.go
> +			if strings.HasPrefix(container.Image, fmt.Sprintf("%s:", imageRepository)) || container.Name == ProxySidecarContainerName {
Addressed

2025-03-11 11:56 UTC, devjoes commented on pkg/webhook/webhook.go
> +
Addressed

2025-03-25 02:06 UTC, enj commented on pkg/webhook/webhook.go
> +	useNativeSidecar, err := util.AssertK8sMinVersion(k8sConfig, 1, 28)
Looks like `SidecarContainers` went beta in 1.29.  With the 3 version supported skew between API server and kubelet, I think 1.32 is earliest version we can enable this.

```suggestion
	useNativeSidecar, err := util.AssertK8sMinVersion(k8sConfig, 1, 32)
```

2025-03-25 10:23 UTC, devjoes commented on pkg/webhook/webhook.go
> +	useNativeSidecar, err := util.AssertK8sMinVersion(k8sConfig, 1, 28)
Good spot, updated

2025-03-31 22:47 UTC, aramase commented
/azp run

2025-04-08 15:26 UTC, aramase commented
/azp run

2025-04-08 19:47 UTC, aramase commented
/azp run

2025-04-08 20:17 UTC, aramase commented
/azp run

2025-04-08 21:14 UTC, aramase commented
/azp run

2025-04-08 21:17 UTC, enj approved these changes

2025-04-08 21:36 UTC, aramase commented
Simulated test failure succesfully: https://github.com/Azure/azure-workload-identity/pull/1588#issuecomment-2787718183

2025-04-08 21:39 UTC, merged